### ISSUE TITLE
不能添加至群

### ISSUE THREAD

**Issue by oxyroid** [imlonghao/nbnhhsh_bot#2]

**Comment by imlonghao** [comment]
这个 bot 本来就不能被添加进群吧

**Comment by oxyroid** [comment]
帮助信息里说的群聊回复别人信息是指？

**Comment by imlonghao** [comment]
先用着别人的 bot 吧，我这个 bot 部署得有点问题，太慢了

在聊天框里输入
`@nbnhhshBot xxx`

**Comment by imlonghao** [comment]
我已经做出了一些调整，可以再试试现在的响应速度如何了。
